"""Guided first-run configuration — writes a .env at the project root.

Interactive by default; every prompt shows the accepted range and a safe
starting value. Run with ``--defaults`` to write a demo-ready .env
non-interactively (credentials left blank for you to fill in).

Usage:
    uv run python scripts/setup.py
    uv run python scripts/setup.py --defaults
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = ROOT / ".env"

# (env var, prompt, default, (lo, hi) or None for free text)
THRESHOLDS: list[tuple[str, str, float, tuple[float, float]]] = [
    (
        "TOPK_MIN_CONFIDENCE",
        "Min direction confidence (fraction of Monte-Carlo paths that must "
        "agree with the mean direction). Wider = more entries, noisier.",
        0.60,
        (0.50, 0.95),
    ),
    (
        "TOPK_MAX_UNCERTAINTY",
        "Max uncertainty (std of predicted return relative to |mean|). "
        "Large values act only as a degenerate-signal safety bound.",
        5.0,
        (1.0, 100.0),
    ),
    (
        "TOPK_MIN_PREDICTED_RETURN",
        "Min predicted return over the prediction horizon (0.001 = 0.1%).",
        0.001,
        (0.0, 0.02),
    ),
    (
        "TOPK_CORRELATION_MAX",
        "Correlation filter: max |Pearson| vs already-selected symbols (1.0 disables the filter).",
        0.75,
        (0.5, 1.0),
    ),
    (
        "RISK_PER_TRADE_PCT",
        "Fraction of equity risked per trade (0.01 = 1%).",
        0.01,
        (0.001, 0.05),
    ),
]

CREDENTIALS: list[tuple[str, str]] = [
    ("IG_DEMO_API", "IG demo API key"),
    ("IG_DEMO_USERNAME", "IG demo username"),
    ("IG_DEMO_PASSWORD", "IG demo password"),
    ("EODHD_API", "EODHD API token (intraday + WebSocket plan)"),
    ("KRONOS_DIR", "Absolute path to your Kronos checkout (the dir containing model/)"),
]


def _ask_float(name: str, help_text: str, default: float, lo: float, hi: float) -> float:
    print(f"\n{name}\n  {help_text}\n  Range [{lo} .. {hi}], default {default}")
    while True:
        raw = input(f"  {name} [{default}]: ").strip()
        if not raw:
            return default
        try:
            val = float(raw)
        except ValueError:
            print("  Not a number — try again.")
            continue
        if lo <= val <= hi:
            return val
        print(f"  Out of range [{lo} .. {hi}] — try again.")


def _ask_text(name: str, help_text: str) -> str:
    return input(f"\n{name} — {help_text}\n  {name}: ").strip()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--defaults",
        action="store_true",
        help="write a demo-ready .env non-interactively (credentials left blank)",
    )
    parser.add_argument(
        "--force", action="store_true", help="overwrite an existing .env without asking"
    )
    args = parser.parse_args()

    if ENV_PATH.exists() and not args.force:
        answer = "" if args.defaults else input(".env already exists — overwrite? [y/N]: ")
        if answer.strip().lower() != "y":
            print("Aborted; existing .env untouched. Use --force to overwrite.", file=sys.stderr)
            return 1

    values: dict[str, str] = {
        "BROKER": "ig",
        "BOT_ENV": "demo",
        "CANDLE_EXCHANGE": "eodhd",
        "CANDLE_TIMEFRAME": "1h",
        "TOPK_ENABLED": "true",
        "TOPK_AGGREGATE_TO_MINUTES": "1",
    }

    if args.defaults:
        for name, _help, default, _rng in THRESHOLDS:
            values[name] = str(default)
        for name, _help in CREDENTIALS:
            values[name] = ""
    else:
        print("== async-trading-engine first-run setup ==")
        print("Press Enter to accept a default. Credentials are stored only in .env")
        print("(gitignored — never commit it).")
        for name, help_text in CREDENTIALS:
            values[name] = _ask_text(name, help_text)
        print("\n-- Signal thresholds --")
        print("These start WIDE on purpose: they only reject degenerate signals.")
        print("After a few weeks of logged signals, tighten them with")
        print("`uv run python scripts/calibrate_thresholds.py` using your own data.")
        for name, help_text, default, (lo, hi) in THRESHOLDS:
            values[name] = str(_ask_float(name, help_text, default, lo, hi))

    lines = ["# Generated by scripts/setup.py — see .env.example for every option."]
    lines += [f"{key}={val}" for key, val in values.items()]
    ENV_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    ENV_PATH.chmod(0o600)

    print(f"\nWrote {ENV_PATH} (0600).")
    blank = [k for k, v in values.items() if not v]
    if blank:
        print("Still blank (fill in before starting the bot): " + ", ".join(blank))
    print("Start the bot with: uv run python -m bot.main")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
